# routeName: the name of route must contain on the path
#      path: 'test' (regex of URL)
#      controller: controllerName
#      methode: methodeToCall
routes:
  home:
    path: '#home|index\.?(php)?$#i'
    controller: 'HomeController'
    methode: 'index'

  billets:
    path: '#billets#i'
    controller: 'PostsController'
    methode: 'getAllposts'

  billet:
    path: '#billet/[1-9]{1,}$#i'
    controller: 'PostsController'
    methode: 'getPost'

  login:
    path: '#login$#i'
    controller: 'LoginController'
    methode: 'log'
  
  disconnect:
    path: '#disconnect$#i'
    controller: 'LoginController'
    methode: 'disconnect'
  
  register:
    path: '#register$#i'
    controller: 'LoginController'
    methode: 'register'
  
  admin:
    path: '#admin$#i'
    controller: 'AdminController'
    methode: 'index'

  admin/add:
    path: '#admin/add$#i'
    controller: 'AdminController'
    methode: 'addPost'

  admin/update:
    path: '#admin/update/[1-9]{1,}$$#i'
    controller: 'AdminController'
    methode: 'update'
  
  admin/delete:
    path: '#admin/delete/[1-9]{1,}$$#i'
    controller: 'AdminController'
    methode: 'delete'



#if roads need to log and a specific role 
firewall:
  admin:
    route: 'admin'
    role: 'admin'

#if app need login controller 
login: 
 controller: LoginController
 methode: log