# routeName:
#      path: 'test' (regex of URL)
#      controller: controllerName
#      methode: methodeToCall

home:
  path: '#index\.?(php)?$#i'
  controller: 'HomeController'
  methode: 'index'

billet:
  path: '#billet/[1-9]{1,}$#i'
  controller: 'BilletController'
  methode: 'index'
